name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test_root:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: [ '1.19', '1.20' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run go tests
        run: go test ./...
